In [6]:
class bike():
    gears = 6

In [7]:
bike1 = bike() #object

In [8]:
bike1.gears

6

In [15]:
class area():
    def calarea(self):
        return 'hi'

In [16]:
area1 = area()

In [17]:
area1.calarea()

'hi'

In [24]:
#process 1:
class room():
    length = 0
    breadth = 0
    def calculated_area(self, length, breadth):
        self.length = length 
        self.breadth = breadth
        return f"{length* breadth}.m2"
    

In [25]:
room1 = room()
room1.calculated_area(400, 532)

'212800.m2'

In [26]:
#direct procedure:
class room():
    def calculated_area1(self, length, breadth):
        return f"{length* breadth}.m2"

In [23]:
room1 = room()
room1.calculated_area1(400, 532)

'212800.m2'

### NumPy:


In [32]:
import numpy as np

In [33]:
np.__version__

'1.24.3'

'''
NumPy provides a array data type which takes 
homogeneous type of elements
'''



In [34]:
#Creating an 1D array:

array1 = np.array([3,4,5,6,7])
array1

array([3, 4, 5, 6, 7])

In [44]:
array1.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [48]:
arr = np.array([3,4,6,7])

In [49]:
arr

array([3, 4, 6, 7])

In [50]:
arr.ndim

1

In [51]:
arr1 = np.array([[4,5,6,6], [3,4,5,6]]) #2D-Array 
arr1

array([[4, 5, 6, 6],
       [3, 4, 5, 6]])

In [52]:
arr1.ndim

2

In [53]:
arr2 = np.array([[[4,5,6,7],[8,7,6,1], [7,2,0,1]]]) #3D-Array
arr2

array([[[4, 5, 6, 7],
        [8, 7, 6, 1],
        [7, 2, 0, 1]]])

In [54]:
arr2.ndim

3

In [56]:
arr2.shape

(1, 3, 4)

In [57]:
arr2.size

12

In [58]:
array1.shape

(5,)

In [59]:
arr3 = np.arange(1,11)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr4 = np.arange(2,11,2)
arr4

array([ 2,  4,  6,  8, 10])

In [62]:
arr5 = np.zeros((3,4)).astype('int64')
arr5

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [66]:
#Pattern Questions:
for i in range(1,10):
    print('*'*i)

*
**
***
****
*****
******
*******
********
*********


In [68]:
arr6 = np.ones((4,5)).astype('int64')
arr6

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [69]:
arr7 = np.full((4,4),5)
arr7

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [73]:
arr8 = np.eye(4,4).astype('int64') #Identity Matrix
arr8

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int64)

In [76]:
arr9 = np.linspace(1,10)
arr9

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [81]:
arr10 = np.linspace(0,10,5)
arr10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [86]:
arr11 = np.random.rand()
arr11

0.35751234543407695

In [90]:
np.random.rand(1,10)

array([[0.34294083, 0.52536811, 0.84294665, 0.87623935, 0.69142267,
        0.42560706, 0.59353849, 0.93294043, 0.00421063, 0.96045239]])

In [91]:
np.random.rand(1,10)*100

array([[78.18213283, 53.82317262, 73.67456111, 54.90499967, 98.73172179,
        64.05744908, 64.98088323, 48.5912433 , 97.0765616 , 98.36746387]])

In [92]:
np.random.randint(1,10)

9

In [94]:
np.random.randint(1,100)

84

In [95]:
np.random.randint(1,100,(3,4))

array([[30, 42,  3, 76],
       [ 7, 23, 21, 30],
       [51,  3, 92, 64]])

In [96]:
#Arithmetic operations:

In [99]:
a = np.array([2,35,66,43])
b = np.random.randint(1,100,(4))
a


array([ 2, 35, 66, 43])

In [98]:
b

array([ 1, 23, 52,  8])

In [100]:
a+b

array([ 91, 133, 121,  51])

In [101]:
np.add(a,b)

array([ 91, 133, 121,  51])

In [110]:
np.subtract(a,b)

array([-87, -63,  11,  35])

In [109]:
np.multiply(a,b)

array([ 178, 3430, 3630,  344])

In [111]:
np.divide(a,b)

array([0.02247191, 0.35714286, 1.2       , 5.375     ])

In [114]:
np.divmod(a,b)

(array([0, 0, 1, 5]), array([ 2, 35, 11,  3]))

In [115]:
np.log(a)

array([0.69314718, 3.55534806, 4.18965474, 3.76120012])

In [117]:
np.sqrt(a)

array([1.41421356, 5.91607978, 8.1240384 , 6.55743852])

In [120]:
np.sin(a) #values are in radiant

array([ 0.90929743, -0.42818267, -0.02655115, -0.83177474])

In [121]:
a

array([ 2, 35, 66, 43])

In [122]:
np.tan(a)

array([-2.18503986,  0.47381472,  0.02656052, -1.49838734])

In [123]:
1/np.tan(a)

array([-0.45765755,  2.11052962, 37.64986844, -0.66738418])

In [124]:
np.sin(a)/np.cos(a)

array([-2.18503986,  0.47381472,  0.02656052, -1.49838734])

In [125]:
np.cos(a)/np.sin(a)

array([-0.45765755,  2.11052962, 37.64986844, -0.66738418])